In [ ]:
import numpy as nnp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Assigning features and label variables
# First Feature
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
# Second Feature
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

# Label or target varible
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [ ]:
df={'weather':['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy'], 'temp':['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'],'play':['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']
}

In [ ]:
df=pd.DataFrame(df)
df

weather  temp play
0      Sunny   Hot   No
1      Sunny   Hot   No
2   Overcast   Hot  Yes
3      Rainy  Mild  Yes
4      Rainy  Cool  Yes
5      Rainy  Cool   No
6   Overcast  Cool  Yes
7      Sunny  Mild   No
8      Sunny  Cool  Yes
9      Rainy  Mild  Yes
10     Sunny  Mild  Yes
11  Overcast  Mild  Yes
12  Overcast   Hot  Yes
13     Rainy  Mild   No

In [ ]:
df.shape

(14, 3)

In [ ]:
df.head()

weather  temp play
0     Sunny   Hot   No
1     Sunny   Hot   No
2  Overcast   Hot  Yes
3     Rainy  Mild  Yes
4     Rainy  Cool  Yes

In [ ]:
df.tail()

weather  temp play
9      Rainy  Mild  Yes
10     Sunny  Mild  Yes
11  Overcast  Mild  Yes
12  Overcast   Hot  Yes
13     Rainy  Mild   No

In [ ]:
df.isnull().sum()

weather    0
temp       0
play       0
dtype: int64

In [ ]:
df.duplicated().sum()

3

In [ ]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12     True
13    False
dtype: bool

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le1 = le.fit_transform(weather)
le1

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le2 = le.fit_transform(temp)
le2

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le3 = le.fit_transform(play)
le3

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [ ]:
#Alternative to spliting in iloc
x=list(zip(le1,le2))
y=le3

In [ ]:
x

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [ ]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5,metric='minkowski')
model1 =model.fit(X_train, y_train)
model1

KNeighborsClassifier()

In [ ]:
y_pred=model.predict(X_test)
y_pred

array([0, 1, 0])

In [ ]:
model.score(X_test,y_test)

0.3333333333333333

In [ ]:
model.predict([[1,3]])

array([1])