In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/Social_Network_Ads.csv')
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [ ]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Model Building 1 KERNEL
from sklearn.svm import SVC
model = SVC(kernel= 'linear',random_state=0)  #linear as only 2 attributes
model1 = model.fit(X_train,y_train)
model1

SVC(kernel='linear', random_state=0)

In [ ]:
print(model1.predict(sc.transform([[28,83000]])))

[0]


In [ ]:
y_pred=model.predict(X_test)

In [ ]:
#Confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[57,  1],
       [ 6, 16]])

In [ ]:
accuracy_score(y_test,y_pred)

0.9125

In [ ]:
#Model Building 2 RBF
from sklearn.svm import SVC
#rbf=Radial Basis Function
model = SVC(kernel= 'rbf',random_state=0)
model2 = model.fit(X_train,y_train)
model2

SVC(random_state=0)

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
#Confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[55,  3],
       [ 1, 21]])

In [ ]:
accuracy_score(y_test,y_pred)

0.95

**NEW DATASET**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.svm import LinearSVC
from sklearn.svm import SVC

In [ ]:
df=pd.read_csv('/content/bank_new.csv')
df

age  job  marital  education  default  balance  housing  loan  contact  \
0       59    0        1          1        0     2343        1     0        2   
1       56    0        1          1        0       45        0     0        2   
2       41    9        1          1        0     1270        1     0        2   
3       55    7        1          1        0     2476        1     0        2   
4       54    0        1          2        0      184        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
11157   33    1        2          0        0        1        1     0        0   
11158   39    7        1          1        0      733        0     0        2   
11159   32    9        2          1        0       29        0     0        0   
11160   43    9        1          1        0        0        0     1        0   
11161   34    9        1          1        0        0        0     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  deposit  
0        5      8      1042         1     -1         0         3        1  
1        5      8      1467         1     -1         0         3        1  
2        5      8      1389         1     -1         0         3        1  
3        5      8       579         1     -1         0         3        1  
4        5      8       673         2     -1         0         3        1  
...    ...    ...       ...       ...    ...       ...       ...      ...  
11157   20      0       257         1     -1         0         3        0  
11158   16      6        83         4     -1         0         3        0  
11159   19      1       156         2     -1         0         3        0  
11160    8      8         9         2    172         5         0        0  
11161    9      5       628         1     -1         0         3        0  

[11162 rows x 17 columns]

In [ ]:
df.shape

(11162, 17)

In [ ]:
df.describe()

age           job       marital     education       default  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948      4.487905      1.199337      1.285164      0.015051   
std       11.913369      3.225132      0.625552      0.749478      0.121761   
min       18.000000      0.000000      0.000000      0.000000      0.000000   
25%       32.000000      1.000000      1.000000      1.000000      0.000000   
50%       39.000000      4.000000      1.000000      1.000000      0.000000   
75%       49.000000      7.000000      2.000000      2.000000      0.000000   
max       95.000000     11.000000      2.000000      3.000000      1.000000   

            balance       housing          loan       contact           day  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean    1528.538524      0.473123      0.130801      0.489697     15.658036   
std     3225.413326      0.499299      0.337198      0.818724      8.420740   
min    -6847.000000      0.000000      0.000000      0.000000      1.000000   
25%      122.000000      0.000000      0.000000      0.000000      8.000000   
50%      550.000000      0.000000      0.000000      0.000000     15.000000   
75%     1708.000000      1.000000      0.000000      1.000000     22.000000   
max    81204.000000      1.000000      1.000000      2.000000     31.000000   

              month      duration      campaign         pdays      previous  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean       5.445709    371.993818      2.508421     51.330407      0.832557   
std        3.191939    347.128386      2.722077    108.758282      2.292007   
min        0.000000      2.000000      1.000000     -1.000000      0.000000   
25%        3.000000    138.000000      1.000000     -1.000000      0.000000   
50%        6.000000    255.000000      2.000000     -1.000000      0.000000   
75%        8.000000    496.000000      3.000000     20.750000      1.000000   
max       11.000000   3881.000000     63.000000    854.000000     58.000000   

           poutcome       deposit  
count  11162.000000  11162.000000  
mean       2.477782      0.473840  
std        1.002952      0.499338  
min        0.000000      0.000000  
25%        2.000000      0.000000  
50%        3.000000      0.000000  
75%        3.000000      1.000000  
max        3.000000      1.000000

In [ ]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.dtypes

age          int64
job          int64
marital      int64
education    int64
default      int64
balance      int64
housing      int64
loan         int64
contact      int64
day          int64
month        int64
duration     int64
campaign     int64
pdays        int64
previous     int64
poutcome     int64
deposit      int64
dtype: object

In [ ]:
'''
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
'''

# Alternative to iloc
x=df.drop('deposit',axis=1)
y=df['deposit']

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
#HARD MARGIN
linsvc=LinearSVC(random_state=0)  #Support vector machine linear
linsvc.fit(xtrain,ytrain)
ypred=linsvc.predict(xtest)
ypred

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report #classification report
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))
train=linsvc.score(xtrain,ytrain)
test=linsvc.score(xtest,ytest)
print(f"Training score : {train} \nTesting score:{test}")

[[1014  191]
 [ 479  549]]
              precision    recall  f1-score   support

           0       0.68      0.84      0.75      1205
           1       0.74      0.53      0.62      1028

    accuracy                           0.70      2233
   macro avg       0.71      0.69      0.69      2233
weighted avg       0.71      0.70      0.69      2233

Training score : 0.6927987456602083 
Testing score:0.6999552171965965


In [ ]:
#SOFT MARGIN
linsvc1=LinearSVC(random_state=0,C=0.8)  #c is 0.8
linsvc1.fit(xtrain,ytrain)
ypred=linsvc1.predict(xtest)
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))
train=linsvc1.score(xtrain,ytrain)
test=linsvc1.score(xtest,ytest)
print(f"Training score:{train}\nTesting score:{test}")

[[1013  192]
 [ 479  549]]
              precision    recall  f1-score   support

           0       0.68      0.84      0.75      1205
           1       0.74      0.53      0.62      1028

    accuracy                           0.70      2233
   macro avg       0.71      0.69      0.69      2233
weighted avg       0.71      0.70      0.69      2233

Training score:0.6929107402844663
Testing score:0.6995073891625616


In [ ]:
# SVC with kernel- polynomial -Hard margin
poly=SVC(random_state=0,kernel='poly',degree=2)
poly.fit(xtrain,ytrain)
ypred=poly.predict(xtest)
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))
train=poly.score(xtrain,ytrain)
test=poly.score(xtest,ytest)
print(f"Training score:{train}\nTesting score:{test}")

[[1097  108]
 [ 607  421]]
              precision    recall  f1-score   support

           0       0.64      0.91      0.75      1205
           1       0.80      0.41      0.54      1028

    accuracy                           0.68      2233
   macro avg       0.72      0.66      0.65      2233
weighted avg       0.71      0.68      0.66      2233

Training score:0.676223541270019
Testing score:0.6798029556650246


In [ ]:
# SVC with kernel- polynomial -soft margin
poly=SVC(random_state=0,kernel='poly',degree=2,C=0.5)
poly.fit(xtrain,ytrain)
ypred=poly.predict(xtest)
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))
train=poly.score(xtrain,ytrain)
test=poly.score(xtest,ytest)
print(f"Training score:{train}\nTesting score:{test}")

[[1110   95]
 [ 637  391]]
              precision    recall  f1-score   support

           0       0.64      0.92      0.75      1205
           1       0.80      0.38      0.52      1028

    accuracy                           0.67      2233
   macro avg       0.72      0.65      0.63      2233
weighted avg       0.71      0.67      0.64      2233

Training score:0.6600963153768619
Testing score:0.6721898790864308


In [ ]:
# SVC with kernel- rbf -soft margin
rbf=SVC(random_state=0,kernel='rbf',C=0.5)
rbf.fit(xtrain,ytrain)
ypred=rbf.predict(xtest)
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))
train=rbf.score(xtrain,ytrain)
test=rbf.score(xtest,ytest)
print(f"Training score:{train}\nTesting score:{test}")

[[985 220]
 [372 656]]
              precision    recall  f1-score   support

           0       0.73      0.82      0.77      1205
           1       0.75      0.64      0.69      1028

    accuracy                           0.73      2233
   macro avg       0.74      0.73      0.73      2233
weighted avg       0.74      0.73      0.73      2233

Training score:0.7397244932243252
Testing score:0.7348858038513211


In [ ]:
# SVC with kernel- radial -hard margin
rbf=SVC(random_state=0,kernel='rbf')
rbf.fit(xtrain,ytrain)
ypred=rbf.predict(xtest)
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))
train=rbf.score(xtrain,ytrain)
test=rbf.score(xtest,ytest)
print(f"Training score:{train}\nTesting score:{test}")

[[980 225]
 [364 664]]
              precision    recall  f1-score   support

           0       0.73      0.81      0.77      1205
           1       0.75      0.65      0.69      1028

    accuracy                           0.74      2233
   macro avg       0.74      0.73      0.73      2233
weighted avg       0.74      0.74      0.73      2233

Training score:0.7436443050733564
Testing score:0.7362292879534259
